services:
  app:
    container_name: migration_app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/back:/application/logs
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=su
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com

  database:
    container_name: migration_database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=su
    volumes:
      - ./data/db:/var/lib/postgresql/data

  nginx:
    build: nginx
    container_name: migration_nginx_proxy
    ports:
      - "80:80"