services:
  app:
    container_name: migration_app
    image: mikhailok/migration-db:0.8
    ports:
      - "8080:8080"
    volumes:
      - ./data/back:/logs
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=197319792001
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com

  database:
    container_name: migration_database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=197319792001
    volumes:
      - ./data/db:/var/lib/postgresql/data

  nginx:
    image: mikhailok/nginx-proxy:0.1
    container_name: migration_nginx_proxy
    ports:
      - "80:80"