services:
  app:
    container_name: migration_app
    image: mikhailok/migration-db:0.3
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=197319792001

  database:
    container_name: migration_database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=migration_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=migration_database
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=197319792001

  nginx:
    image: mikhailok/nginx-proxy:0.1
    container_name: migration_nginx_proxy
    ports:
      - "80:80"