spring:
  application:
    name: migration-db
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:migration_database}
    username: ${POSTGRES_USER:application}
    password: ${POSTGRES_PASSWORD:197319792001}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: false
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    path: ./logs/

springdoc:
  api-docs:
    path: /api-docs

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}
  email: ${ADMIN_EMAIL:admin@example.com}