spring:
  application:
    name: migration-db
  datasource:
    url: jdbc:h2:mem:migration-db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    name: "applicationLogs.log"
    path: /
