services:
  database-bank-1:
    container_name: database_bank_orig
    image: 'postgres:15-alpine'
    ports:
      - "54323:5432"
    env_file:
      - env_files/db1.env
    volumes:
      - ./scripts/init:/docker-entrypoint-initdb.d/
  database-bank-2:
    container_name: database_bank_copy
    image: postgres:15-alpine
    ports:
      - "54324:5432"
    env_file:
      - env_files/db2.env
    volumes:
      - ./scripts/init_2:/docker-entrypoint-initdb.d/