package ru.rtu_mirea.migrationdb.component.sql;

import ru.rtu_mirea.migrationdb.entity.ColumnInfo;
import ru.rtu_mirea.migrationdb.entity.RelationData;

import java.util.ArrayList;
import java.util.Map;

public class CreateSQL {
    public String createSQLForTable(String tableName,
                                    ArrayList<ColumnInfo> tableColumns,
                                    Map<String, ArrayList<RelationData>> relations,
                                    Map<String, ArrayList<String>> primaryKeys) {
        StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS " + tableName  + " (");
        ArrayList<RelationData> tableRelations = relations.get(tableName);
        int flag = 0;
        for (ColumnInfo column : tableColumns) {
            sql.append(column.columnName()).append(" ").append(column.dataType());
            if (column.isNullable()) {
                sql.append(" NULL");
            } else {
                sql.append(" NOT NULL");
            }
            if (column.isIdentity()) {
                if (column.identityGeneration().equals("ALWAYS")) {
                    sql.append(" GENERATED ALWAYS AS IDENTITY");
                } else {
                    sql.append(" GENERATED BY DEFAULT AS IDENTITY");
                }
            }
            if (column.columnDefault() != null) {
                sql.append(" DEFAULT ").append(column.columnDefault());
            }
            ArrayList<String> primaryKeysForTable = primaryKeys.get(tableName);
            if (primaryKeysForTable != null && primaryKeysForTable.size() == 1 && primaryKeysForTable.contains(column.columnName())) {
                sql.append(" PRIMARY KEY");
            }
            if (flag != tableColumns.size() - 1 && tableRelations != null) {
                sql.append(",");
                flag++;
            }
        }

        ArrayList<String> primaryKeysForTable = primaryKeys.get(tableName);
        if (primaryKeysForTable != null && primaryKeysForTable.size() > 1) {
            sql.append(", PRIMARY KEY (");
            for (int i = 0; i < primaryKeysForTable.size(); i++) {
                sql.append(primaryKeysForTable.get(i));
                if (i != primaryKeysForTable.size() - 1) {
                    sql.append(", ");
                }
            }
            sql.append(")");
        }

        // Add foreign keys
        if (tableRelations != null) {
            for (RelationData relation : tableRelations) {
                sql.append(", FOREIGN KEY (").append(relation.columnName()).append(") REFERENCES ")
                        .append(relation.refTableName()).append("(").append(relation.refColumnName())
                        .append(")");
            }
        }

        sql.append(")");
        return sql.toString();
    }
}
